name: Build Docker Image and Notify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: my-python-app

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      id: build
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Notify Slack on Success
      if: success()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "✅ Docker Build Success",
            "attachments": [
              {
                "color": "good",
                "fields": [
                  {
                    "title": "Image",
                    "value": "${{ env.IMAGE_NAME }}:${{ steps.build.outputs.image_tag }}",
                    "short": true
                  },
                  {
                    "title": "Branch",
                    "value": "${{ github.ref }}",
                    "short": true
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Slack on Failure
      if: failure()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "❌ Docker Build Failed",
            "attachments": [
              {
                "color": "danger",
                "fields": [
                  {
                    "title": "Image",
                    "value": "${{ env.IMAGE_NAME }}",
                    "short": true
                  },
                  {
                    "title": "Branch",
                    "value": "${{ github.ref }}",
                    "short": true
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}