name: Build Docker Image and Notify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: my-python-app

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      id: build
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Notify Slack on Success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: "✅ Docker Build Success\n*Image:* ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}"
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Slack on Success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: "✅ Docker Build Success\n*Image:* ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}"
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}